import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { readFile, mkdir } from "node:fs/promises";
import { resolve, extname, sep } from "node:path";
import { once } from "node:events";
import { chromium } from "playwright";
import { unzipSync, strFromU8 } from "fflate";

test("Pages starts with local Bundle Import and exports without a server", async () => {
  const root = resolve("dist-pages");
  const server = createServer(async (req, res) => {
    const path = resolve(root, "." + new URL(req.url, "http://localhost").pathname.replace(/^\/pack-qa-checker/, "").replace(/\/$/, "/index.html"));
    if (!path.startsWith(root + sep)) { res.writeHead(403); return res.end(); }
    try {
      const bytes = await readFile(path);
      res.setHeader("Content-Type", { ".js": "text/javascript", ".css": "text/css", ".html": "text/html" }[extname(path)] || "application/octet-stream");
      res.end(bytes);
    } catch { res.writeHead(404); res.end(); }
  }).listen(0, "127.0.0.1");
  await once(server, "listening");
  let browser;
  try {
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();
    const errors = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/pack-qa-checker/`);
    await page.getByText("แปลงตารางเป็น Bundle พร้อม Import", { exact: true }).waitFor();
    assert.equal(await page.getByText("เซิร์ฟเวอร์ Request และ History", { exact: true }).count(), 0);
    const textarea = page.locator("textarea").first();
    await textarea.fill("1315002\tGod Fellow Ticket\t30");
    await page.getByText("God Fellow Ticket", { exact: true }).first().waitFor();
    const selection = page.locator(".bundle-preview-top input[type=checkbox]").first();
    await selection.check();
    assert.equal(await selection.isChecked(), true);
    await textarea.fill("1315002\tGod Fellow Ticket\t31");
    await page.waitForFunction(() => !document.querySelector(".bundle-preview-top input[type=checkbox]")?.checked);
    assert.equal(await selection.isChecked(), false, "Editing bundle contents must invalidate its old lock");
    await page.getByText("ข้อมูลเปลี่ยนหลังล็อก กรุณาเลือก Bundle ที่ต้องการส่งออกใหม่", { exact: true }).waitFor();
    assert.equal(await page.getByRole("button", { name: /Export Import file/ }).isDisabled(), true);
    await textarea.fill("Bundle Name\tA\nItem ID\tItem Name\tAmt\n51201\tLanistar Key\t1\n\nBundle Name\tB\nItem ID\tItem Name\tAmt\n52001\tMemory Key\t2");
    await page.getByLabel("ชื่อ Bundle 1").fill("Bundle ที่หนึ่ง");
    await page.getByLabel("ชื่อ Bundle 2").fill("Bundle ที่สอง");
    assert.equal(await page.getByLabel("ชื่อ Bundle 1").inputValue(), "Bundle ที่หนึ่ง");
    assert.equal(await page.getByLabel("ชื่อ Bundle 2").inputValue(), "Bundle ที่สอง");
    await selection.check();
    assert.equal(await page.getByRole("button", { name: "Export Import file (1)", exact: true }).isEnabled(), true);
    await selection.uncheck();
    assert.equal(await page.getByRole("button", { name: /Export Import file/ }).isDisabled(), true, "Unchecking the last bundle must not select all");
    await page.getByRole("button", { name: "ล็อกทั้งหมด", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "Export Import file (2)", exact: true }).isEnabled(), true);
    await textarea.fill("Bundle Name\tInvalid demo\nItem ID\tItem Name\tAmt\tChance\n51201\tLanistar Key\t1\t100\n52001\tMemory Key\t1\t");
    assert.equal(await page.getByRole("button", { name: /Export Import file/ }).isDisabled(), true, "Missing rates must block partial exports");
    await textarea.fill("Item ID\tItem Name\tAmt\tAmt\tAmt\n51201\tLanistar Key\t100\t70\t50");
    await page.getByText(/พบหลายชุดข้อมูลในแนวนอน/).first().waitFor();
    assert.equal(await page.getByRole("button", { name: /Export Import file/ }).count(), 0);
    await textarea.fill("1315002\tGod Fellow Ticket\t31");
    await mkdir("../outputs/pages-review", { recursive: true });
    await page.getByLabel("ชื่อ Bundle 1").fill("ทดสอบ Export local");
    await selection.check();
    let localApiCalls = 0;
    await page.route("**/api/bundle-import", route => { localApiCalls++; return route.abort(); });
    await page.route("**/api/product-import", route => { localApiCalls++; return route.abort(); });
    const localDownload = page.waitForEvent("download");
    await page.getByRole("button", { name: /Export Import file/ }).click();
    const zipped = await localDownload;
    assert.match(zipped.suggestedFilename(), /\.zip$/);
    const zipEntries = unzipSync(await readFile(await zipped.path()));
    assert.equal(Object.keys(zipEntries).length, 1);
    assert.match(Object.keys(zipEntries)[0], /ทดสอบ Export local/);
    const workbook = unzipSync(Object.values(zipEntries)[0]);
    const original = unzipSync(await readFile("templates/bundle-import-template.xlsx"));
    for (const key of Object.keys(original).filter(key => !["xl/worksheets/sheet1.xml", "xl/sharedStrings.xml"].includes(key))) assert.deepEqual(workbook[key], original[key], key);
    assert.match(strFromU8(workbook["xl/worksheets/sheet1.xml"]), /r="E2"[^>]*><v>31<\/v>/);
    assert.match(strFromU8(workbook["xl/sharedStrings.xml"]), /ทดสอบ Export local/);
    await page.getByLabel("รูปแบบไฟล์ Export").selectOption("xlsx");
    const combinedDownload = page.waitForEvent("download");
    await page.getByRole("button", { name: /Export Import file/ }).click();
    const combined = unzipSync(await readFile(await (await combinedDownload).path()));
    assert.deepEqual(combined["xl/worksheets/sheet1.xml"], workbook["xl/worksheets/sheet1.xml"]);
    assert.equal(await page.getByRole("button", { name: "Export Product Import", exact: true }).count(), 0);
    assert.equal(localApiCalls, 0, "Standalone exports must never call the API");
    await page.screenshot({ path: "../outputs/pages-review/desktop.png", fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "../outputs/pages-review/mobile.png", fullPage: true });
    const request = { id: "SMOKE1", title: "Saved request", request_type: "ITEM_CODE", status: "REVIEW", updated_at: "2026-09-08T00:00:00Z", source_text: "1315002\tGod Fellow Ticket\t30", payload: {} };
    const shop = { ...request, id: "SHOP2", title: "Shop request", request_type: "WEB_SHOP", status: "NEW", notification_status: "FAILED" };
    await page.route("**/api/requests", route => route.fulfill({ json: { requests: [request, shop] } }));
    await page.route("**/api/requests/SMOKE1", route => route.fulfill({ json: { request } }));
    let exportedId;
    await page.route("**/api/bundle-import", route => {
      exportedId = route.request().postDataJSON().requestId;
      return route.fulfill({ contentType: "application/octet-stream", body: "test-download" });
    });
    await page.reload();
    await page.getByRole("button", { name: "Request Hub", exact: true }).click();
    await page.getByLabel("ค้นหางาน", { exact: true }).fill("SHOP2");
    assert.equal(await page.locator(".request-row").count(), 1);
    await page.locator(".request-row summary").click();
    await page.getByText("Discord: แจ้งไม่สำเร็จ", { exact: true }).waitFor();
    const status = page.getByLabel("สถานะ Shop request", { exact: true });
    assert.equal(await status.isVisible(), true, "Mobile must allow status changes");
    await page.route("**/api/requests/SHOP2/status", route => route.fulfill({ status: 500, json: { error: "Status save failed" } }));
    await status.selectOption("IMPORTED");
    await page.getByText("Status save failed", { exact: true }).waitFor();
    assert.equal(await status.inputValue(), "NEW", "Failed saves must not show the new status");
    await page.getByLabel("ค้นหางาน", { exact: true }).fill("");
    await page.getByLabel("กรองสถานะ", { exact: true }).selectOption("IMPORTED");
    await page.getByText("ไม่พบงานที่ตรงกับการค้นหา", { exact: true }).waitFor();
    await page.getByLabel("กรองสถานะ", { exact: true }).selectOption("");
    await page.getByLabel("ประเภทงาน", { exact: true }).selectOption("ITEM_CODE");
    assert.equal(await page.locator(".request-row").count(), 1);
    await page.screenshot({ path: "../outputs/pages-review/request-history-mobile.png", fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.getByRole("button", { name: "เปิดใน Adapter", exact: true }).click();
    await page.getByRole("button", { name: /Export Import file/ }).click();
    await page.waitForFunction(() => !Array.from(document.querySelectorAll("button")).some(b => b.textContent.includes("กำลังสร้างไฟล์")));
    assert.equal(exportedId, "SMOKE1", "Reopening a request without auto rewards must retain its export history ID");
    await page.route("**/api/requests/SHOP2", route => route.fulfill({ json: { request: { ...shop, source_text: "" } } }));
    await page.getByRole("button", { name: "Request Hub", exact: true }).click();
    await page.getByLabel("ค้นหางาน", { exact: true }).fill("SHOP2");
    await page.getByRole("button", { name: "เปิดใน Adapter", exact: true }).click();
    assert.equal(await page.locator("textarea").first().inputValue(), "");
    assert.equal(await page.locator(".bundle-preview").count(), 0, "Empty new request must not inherit previous items");
    assert.equal(await page.getByRole("button", { name: /Export Import file/ }).count(), 0);
    await page.locator("textarea").first().fill("Bundle Name\tNew shop\n1315001\tFellow Ticket\t1");
    await page.getByRole("button", { name: /Export Import file/ }).click();
    await page.waitForFunction(() => !Array.from(document.querySelectorAll("button")).some(b => b.textContent.includes("กำลังสร้างไฟล์")));
    assert.equal(exportedId, "SHOP2");
    await page.reload();
    await page.getByRole("button", { name: "Request Hub", exact: true }).click();
    await page.getByRole("button", { name: /^Web Shop/ }).click();
    await page.getByLabel("ชื่องาน / ชื่อ Product").fill("Validation request");
    const sourceTable = "Product Name\tAuto detect\tLimit\t10\nTHB\tSeed Point\tGSP Earn\tEXP Rank Earn\tItem ID\tItem Name\tAmt\n59\t590\t590\t59\t51201\tLanistar Key\t5";
    await page.locator("textarea").fill(sourceTable);
    await page.waitForFunction(() => Array.from(document.querySelectorAll("input")).some(input => input.value === "590"));
    assert.equal(await page.getByLabel("Seed Point", { exact: true }).inputValue(), "590");
    assert.equal(await page.getByLabel("Purchase limit per player", { exact: true }).inputValue(), "10");
    await page.locator("textarea").fill(sourceTable.replaceAll("590", "790").replace("Limit\t10", "Limit\t7"));
    await page.waitForFunction(() => Array.from(document.querySelectorAll("input")).some(input => input.value === "790"));
    assert.equal(await page.getByLabel("Purchase limit per player", { exact: true }).inputValue(), "7");
    await page.getByLabel("Seed Point", { exact: true }).fill("999");
    await page.locator("textarea").fill(sourceTable);
    assert.equal(await page.getByLabel("Seed Point", { exact: true }).inputValue(), "999", "Manual price must survive source updates");
    await page.getByLabel("Purchase limit per player", { exact: true }).fill("");
    await page.locator("textarea").fill(sourceTable + "\n");
    assert.equal(await page.getByLabel("Purchase limit per player", { exact: true }).inputValue(), "", "Explicit clearing must survive source updates");
    await page.getByRole("button", { name: /^Random/ }).click();
    const submit = page.getByRole("button", { name: "สร้าง Request และ Review Bundle", exact: true });
    await submit.click();
    await page.getByText("เลือกก่อนว่าสินค้าสุ่มมี Fixed rewards หรือไม่", { exact: true }).waitFor();
    await page.getByRole("button", { name: /^ไม่มี/ }).click();
    await page.getByLabel("Seed Point", { exact: true }).fill("abc");
    await submit.click();
    await page.getByText("Seed Point ต้องเป็นตัวเลขตั้งแต่ 0 ขึ้นไป", { exact: true }).waitFor();
    await page.getByLabel("Seed Point", { exact: true }).fill("590.5");
    await page.getByLabel("Purchase limit per player", { exact: true }).fill("1.5");
    await submit.click();
    await page.getByText("Purchase limit per player ต้องเป็นจำนวนเต็มตั้งแต่ 1 ขึ้นไป หรือเว้นว่าง", { exact: true }).waitFor();
    await page.getByText("Golden Seed Point 590.5 · Player EXP 59.05", { exact: true }).waitFor();
    let createdPayload;
    await page.route("**/api/requests", route => {
      if (route.request().method() === "GET") return route.fulfill({ json: { requests: [request, shop] } });
      createdPayload = route.request().postDataJSON();
      return route.fulfill({ json: { request: { ...createdPayload, id: "CREATED1", status: "REVIEW" } } });
    });
    await page.getByLabel("Purchase limit per player", { exact: true }).fill("2");
    await page.locator("textarea").fill("1315002\tGod Fellow Ticket\t1");
    await submit.click();
    await page.getByText("รายการก่อนล็อก", { exact: true }).waitFor();
    assert.equal(createdPayload.payload.seed_point, "590.5");
    assert.equal(createdPayload.payload.auto_rewards.player_exp, 59.05);
    assert.equal(createdPayload.fixed_rewards, false);
    await page.reload();
    await page.getByRole("button", { name: "Request Hub", exact: true }).click();
    await page.getByRole("button", { name: /^Item Code/ }).click();
    await page.getByLabel("ชื่องาน / ชื่อ Bundle").fill("Item code validation");
    await page.getByLabel("ใช้ได้ต่อ User", { exact: true }).fill("-1");
    await page.getByRole("button", { name: "สร้าง Request และ Review Bundle", exact: true }).click();
    await page.getByText("ใช้ได้ต่อ User ต้องเป็นจำนวนเต็มตั้งแต่ 1 ขึ้นไป หรือเว้นว่าง", { exact: true }).waitFor();
    assert.deepEqual(errors, []);
  } finally {
    if (browser) await browser.close();
    await new Promise(resolve => server.close(resolve));
  }
});
